### PR TITLE
[Packaging] Build the runtime from Python   

### PR DESCRIPTION
**Pull request by maliasadi**
This PR lets developers to build runtime from Python supporting any available backends and compilation options following the PL-Lightning approach. 

To install catalyst with the "lightning.qubit" backend simulator:
``` console
$ backend="lightning.qubit" pip install .  # or
$ pip install . # the default is lightning.qubit
$ pip install -e . # the editable mode is also supported
``` 
To install with multiple backend devices:
``` console
$ backend="lightning.qubit;lightning.kokkos;braket.qubit" pip install . 
```

You can also update the C and CXX compilers as follows,
``` console 
$ C_COMPILER="clang-14" CXX_COMPILER="clang++-14" pip install .
```

[sc-36729]

### CODE REVIEW

**Comment by josh146** [comment]
Great job @maliasadi!! Now that this enables building from source via Python, it looks like the readthedocs build is failing.

- Mock out any C python modules [like we do in Kokkos ](https://github.com/PennyLaneAI/pennylane-lightning-kokkos/blob/8dad507709504664550e3a21cd335baac7505fe5/doc/conf.py#L33)

  - Since we don't have any python bindings yet, I don't think we need to do this?

- Update our `.readthedocs.yml` to have the correct dependencies installed (see the kokkos one: https://github.com/PennyLaneAI/pennylane-lightning-kokkos/blob/main/.readthedocs.yml)

**Review by erick-xanadu — COMMENTED** [review]
Looks great!

I normally prefer to have a single way of doing things, with some configuration capabilities. I see some benefits in keeping the current build and installation procedure of the runtime with Makefiles. For example, testing individual devices (PL-lightning, Kokkos) and having different success/failure indicators for each of these steps in Github Actions. However, this brings me to the question: would it make sense to replace the CI/CD scripts to use this installation method? Or would we maintain two different installation methods? What do you think would be best here?

And if we are going to maintain two installation methods, maybe it would make sense to test this installation method in CI/CD to make sure that both of them succeed?

**Comment by josh146** [comment]
> I would it make sense to replace the CI/CD scripts to use this installation method? Or would we maintain two different installation methods? What do you think would be best here?

I would definitely pull in @mlxd and the performance team for comment here, as they have tackled the same problem, and can give us very important insights into the decision they made, and why

**Comment by mlxd** [comment]
> > I would it make sense to replace the CI/CD scripts to use this installation method? Or would we maintain two different installation methods? What do you think would be best here?
> 
> I would definitely pull in @mlxd and the performance team for comment here, as they have tackled the same problem, and can give us very important insights into the decision they made, and why

Hey, good call. I'd request that even with a few comments and approvals, it'd be great if you can hold off on merging this until we have time to review. It'll be next week before that happens though, given the upcoming release.

**Comment by maliasadi** [comment]
I see your points, @erick-xanadu! That's the reason I think we should keep the Makefile in the runtime subdirectory as is for testing and development purposes. However, CI/CD and wheels scripts can be updated to use the new installation method as it would simplify the GH checks scripts and let us to take advantage of `cibuildwheel` and `auditwheel` to facilitate the creation of Python wheels.

**Comment by dime10** [comment]
> However, this brings me to the question: would it make sense to replace the CI/CD scripts to use this installation method? Or would we maintain two different installation methods? What do you think would be best here?

The main concern with our actions is that we use caching efficiently. Not sure that is possible or not with this approach.

**Comment by dime10** [comment]
I don't see any changes to documentation files. Everything shown in the PR description should also show up in the docs somewhere, probably our installation guide.

**Comment by maliasadi** [comment]
We'll get back to this after providing a unified CMake for all C++ modules. Also, due to the recent changes in the wheel recipe and our build system, there is currently no significant benefit to merging this work.

**Pull request closed without merging**
