### PR TITLE
[CI/CD] Use CMake platform agnostic commands

### PR DESCRIPTION
**Pull request by erick-xanadu**
**Context:** While reading CMake's documentation in order to better manage the build process of the compiler driver, I encountered these small cute portable commands.

**Description of the Change:** Change some commands to use CMake commands.

**Benefits:** Portability.

### CODE REVIEW

**Review by maliasadi — APPROVED** [review]
Thanks @erick-xanadu! :slightly_smiling_face: 

We're also using these in [the runtime](https://github.com/PennyLaneAI/catalyst/blob/201b0ec6cbec18b6411a876a3c72ba878123e2a1/runtime/CMakeLists.txt#L29) to install qir-stdlib.

**Comment by maliasadi** [comment]
By the way, the only reason we didn't use them in Makefiles earlier is the fact that Makefile itself is not cross-platform. The better practice here is by using less Make commands and rely more on building from Python or CMake. But it shouldn't block merging this PR.

**Comment by dime10** [comment]
> By the way, the only reason we didn't use them in Makefiles earlier is the fact that Makefile itself is not cross-platform. The better practice here is by using less Make commands and rely more on building from Python or CMake. But it shouldn't block merging this PR.

While I generally I agree with, I'm not so certain it is Make that is the issue. We already use CMake to actually build our projects. Make is merely used as a glorified shell script, and it's not uncommon for projects to have shell scripts to actually launch build/installation processes with a single command. Shell scripts are inherently platform specific though and usually requires one script for each supported platform.

**Comment by maliasadi** [comment]
@dime10 Agree! However my point there is more about moving the logic more into the CMake and setup.py than relying on Make commands or shell scripts when it makes sense.

**Comment by erick-xanadu** [comment]
https://www.gnu.org/software/autoconf/manual/autoconf-2.60/html_node/Programming-in-M4sh.html alternatives in Autotools

**Pull request merged**
