### PR TITLE
Fix scatter op when updatedWindowsDims is empty (unlocks jax grad on slices)

### PR DESCRIPTION
**Pull request by rmoyard**
**Context:**
If `updatedWindowsDims` is empty, the correct `updatedScatterIndices` are all the dimensions and not empty.

**Description of the Change:**
Correct the value of `updatedScatterIndices` when `updatedWindowsDims` is empty.

### CODE REVIEW

**Comment by rmoyard** [comment]
[sc-55109]

**Review by dime10 — APPROVED** [review]
Good catch! Is there an integration example that we can test as well (that made you aware of the issue)? 

Don't forget a changelog :)

**Comment by rmoyard** [comment]
@dime10 It is when you apply you use jax.grad on a sliced tensor, but it is not working anymore because we did not register jvp for gather.

**Comment by dime10** [comment]
> @dime10 It is when you apply you use jax.grad on a sliced tensor, but it is not working anymore because we did not register jvp for gather.

Can we add that as a test?

**Comment by rmoyard** [comment]
Yes we cannot, because we do not support differentiation of gather because the operation was overridden by us https://github.com/PennyLaneAI/catalyst/pull/411/files#r1462447226

**Pull request merged**
