### PR TITLE
Fixing `gather batching rule not implemented` when multiple qjits call them

### LINKED ISSUE #894: Bug with batching rule for `gather` not implemented
Running:

```python
@pytest.mark.parametrize("arg", [jnp.array([[0.1, 0.2], [0.3, 0.4]])])
@pytest.mark.parametrize("order", ["good", "bad"])
def test_vjp_as_residual(arg, order):
    """See https://github.com/PennyLaneAI/catalyst/issues/852"""

    def jax_callback(fn, result_type):

        @pure_callback
        def callback_fn(*args) -> result_type:
            return fn(*args)

        @callback_fn.fwd
        def callback_fn_fwd(*args):
            ans, vjp_func = accelerate(lambda *x: jax.vjp(fn, *x))(*args)
            return ans, vjp_func

        @callback_fn.bwd
        def callback_fn_bwd(vjp_func, dy):
            return accelerate(vjp_func)(dy)

        return callback_fn

    @qml.qjit
    @jacobian
    def hypothesis(x):
        expm = jax_callback(jax.scipy.linalg.expm, jax.ShapeDtypeStruct((2, 2), jnp.float64))
        return expm(x)

    @jax.jacobian
    def ground_truth(x):
        return jax.scipy.linalg.expm(x)

    obs = hypothesis(arg)
    exp = ground_truth(arg)
    assert np.allclose(obs, exp)

```

raises the following error:

```
E     NotImplementedError: Batching rule for 'gather' not implemented

../env/lib/python3.10/site-packages/jax/_src/api.py:945: NotImplementedError
====================================================================================== warnings summary ======================================================================================
frontend/catalyst/jax_extras/tracing.py:92
  /home/ubuntu/code/catalyst/frontend/catalyst/jax_extras/tracing.py:92: DeprecationWarning: jax.linear_util.transformation_with_aux is deprecated. Use jax.extend.linear_util.transformation_with_aux instead.
    from jax.linear_util import transformation_with_aux, wrap_init

frontend/catalyst/jax_extras/tracing.py:92
  /home/ubuntu/code/catalyst/frontend/catalyst/jax_extras/tracing.py:92: DeprecationWarning: jax.linear_util.wrap_init is deprecated. Use jax.extend.linear_util.wrap_init instead.
    from jax.linear_util import transformation_with_aux, wrap_init

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
================================================================================== short test summary info ===================================================================================
FAILED frontend/test/pytest/test_callback.py::test_vjp_as_residual[good-arg0] - NotImplementedError: Batching rule for 'gather' not implemented
FAILED frontend/test/pytest/test_callback.py::test_vjp_as_residual[bad-arg0] - NotImplementedError: Batching rule for 'gather' not implemented
```

But changing the order to

```
    exp = ground_truth(arg)
    obs = hypothesis(arg)
```

passes the test. 

Possibly related to #733

### LINKED ISSUE #1094: [BUG] Can't run `jax.scipy.linalg.solve` and `jax.scipy.linalg.expm` from separate `@qjit` blocks within the same program
If you try to run `solve` and `expm` from separate `@qjit` blocks within the same program, you get a `Batching rule for 'gather' not implemented` error. For example:

```python
import numpy as np

import jax.numpy as jnp
import jax.scipy as jsp

from catalyst import qjit


rng = np.random.default_rng(42)


def bad():
    A = jnp.array(rng.uniform(-1, 1, (3, 3)))
    b = jnp.array(rng.uniform(-1, 1, (3, 1)))

    @qjit
    def f(A, b):
        return jsp.linalg.solve(A, b)
    
    @qjit
    def g(A):
        jsp.linalg.expm(A)

    return f(A, b), g(A)


solve_result, expm_result = bad()
print(solve_result)
print(expm_result)
```

results in:

```
Traceback (most recent call last):
  File ".../test.py", line 73, in <module>
    solve_result, expm_result = bad()
  File ".../test.py", line 70, in bad
    return f(A, b), g(A)
  File ".../.conda/envs/xanadu/lib/python3.9/site-packages/pennylane/logging/decorators.py", line 61, in wrapper_entry
    return func(*args, **kwargs)
  File ".../work/pennylane/catalyst/frontend/catalyst/jit.py", line 457, in __call__
    requires_promotion = self.jit_compile(args, **kwargs)
  File ".../.conda/envs/xanadu/lib/python3.9/site-packages/pennylane/logging/decorators.py", line 61, in wrapper_entry
    return func(*args, **kwargs)
  File ".../work/pennylane/catalyst/frontend/catalyst/jit.py", line 528, in jit_compile
    self.jaxpr, self.out_type, self.out_treedef, self.c_sig = self.capture(
  File ".../work/pennylane/catalyst/frontend/catalyst/debug/instruments.py", line 143, in wrapper
    return fn(*args, **kwargs)
  File ".../.conda/envs/xanadu/lib/python3.9/site-packages/pennylane/logging/decorators.py", line 61, in wrapper_entry
    return func(*args, **kwargs)
  File ".../work/pennylane/catalyst/frontend/catalyst/jit.py", line 610, in capture
    jaxpr, out_type, treedef = trace_to_jaxpr(
  File ".../.conda/envs/xanadu/lib/python3.9/site-packages/pennylane/logging/decorators.py", line 61, in wrapper_entry
    return func(*args, **kwargs)
  File ".../work/pennylane/catalyst/frontend/catalyst/jax_tracer.py", line 536, in trace_to_jaxpr
    jaxpr, out_type, out_treedef = make_jaxpr2(func, **make_jaxpr_kwargs)(*args, **kwargs)
  File ".../work/pennylane/catalyst/frontend/catalyst/jax_extras/tracing.py", line 555, in make_jaxpr_f
    jaxpr, out_type, consts = trace_to_jaxpr_dynamic2(f)
  File ".../work/pennylane/catalyst/frontend/catalyst/jit.py", line 608, in fn_with_transform_named_sequence
    return self.user_function(*args, **kwargs)
  File ".../work/pennylane/catalyst/frontend/test.py", line 64, in f
    return jsp.linalg.solve(A, b)
  File ".../.conda/envs/xanadu/lib/python3.9/site-packages/jax/_src/scipy/linalg.py", line 1022, in solve
    return _solve(a, b, assume_a, lower)
  File ".../.conda/envs/xanadu/lib/python3.9/site-packages/jax/_src/scipy/linalg.py", line 944, in _solve
    return jnp.linalg.solve(a, b)
  File ".../.conda/envs/xanadu/lib/python3.9/site-packages/jax/_src/numpy/linalg.py", line 1320, in solve
    return jnp.vectorize(lax_linalg._solve, signature=signature)(a, b)
  File ".../.conda/envs/xanadu/lib/python3.9/site-packages/jax/_src/numpy/vectorize.py", line 321, in wrapped
    result = vectorized_func(*squeezed_args)
  File ".../.conda/envs/xanadu/lib/python3.9/site-packages/jax/_src/numpy/vectorize.py", line 138, in wrapped
    out = func(*args)
  File ".../.conda/envs/xanadu/lib/python3.9/site-packages/jax/_src/numpy/vectorize.py", line 321, in wrapped
    result = vectorized_func(*squeezed_args)
  File ".../.conda/envs/xanadu/lib/python3.9/site-packages/jax/_src/numpy/vectorize.py", line 138, in wrapped
    out = func(*args)
  File ".../.conda/envs/xanadu/lib/python3.9/site-packages/jax/_src/numpy/vectorize.py", line 181, in new_func
    return func(*args, **kwargs, **static_kwargs)
  File ".../.conda/envs/xanadu/lib/python3.9/site-packages/jax/_src/numpy/array_methods.py", line 739, in op
    return getattr(self.aval, f"_{name}")(self, *args)
  File ".../.conda/envs/xanadu/lib/python3.9/site-packages/jax/_src/numpy/array_methods.py", line 352, in _getitem
    return lax_numpy._rewriting_take(self, item)
  File ".../.conda/envs/xanadu/lib/python3.9/site-packages/jax/_src/numpy/lax_numpy.py", line 5616, in _rewriting_take
    return _gather(arr, treedef, static_idx, dynamic_idx, indices_are_sorted,
  File ".../.conda/envs/xanadu/lib/python3.9/site-packages/jax/_src/numpy/lax_numpy.py", line 5646, in _gather
    y = lax.gather(
jax._src.source_info_util.JaxStackTraceBeforeTransformation: NotImplementedError: Batching rule for 'gather' not implemented

The preceding stack trace is the source of the JAX operation that, once transformed by JAX, triggered the following exception.

--------------------

The above exception was the direct cause of the following exception:

jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File ".../work/pennylane/catalyst/frontend/test.py", line 73, in <module>
    solve_result, expm_result = bad()
  File ".../work/pennylane/catalyst/frontend/test.py", line 70, in bad
    return f(A, b), g(A)
  File ".../.conda/envs/xanadu/lib/python3.9/site-packages/pennylane/logging/decorators.py", line 61, in wrapper_entry
    return func(*args, **kwargs)
  File ".../work/pennylane/catalyst/frontend/catalyst/jit.py", line 457, in __call__
    requires_promotion = self.jit_compile(args, **kwargs)
  File ".../.conda/envs/xanadu/lib/python3.9/site-packages/pennylane/logging/decorators.py", line 61, in wrapper_entry
    return func(*args, **kwargs)
  File ".../work/pennylane/catalyst/frontend/catalyst/jit.py", line 528, in jit_compile
    self.jaxpr, self.out_type, self.out_treedef, self.c_sig = self.capture(
  File ".../work/pennylane/catalyst/frontend/catalyst/debug/instruments.py", line 143, in wrapper
    return fn(*args, **kwargs)
  File ".../.conda/envs/xanadu/lib/python3.9/site-packages/pennylane/logging/decorators.py", line 61, in wrapper_entry
    return func(*args, **kwargs)
  File ".../work/pennylane/catalyst/frontend/catalyst/jit.py", line 610, in capture
    jaxpr, out_type, treedef = trace_to_jaxpr(
  File ".../.conda/envs/xanadu/lib/python3.9/site-packages/pennylane/logging/decorators.py", line 61, in wrapper_entry
    return func(*args, **kwargs)
  File ".../work/pennylane/catalyst/frontend/catalyst/jax_tracer.py", line 536, in trace_to_jaxpr
    jaxpr, out_type, out_treedef = make_jaxpr2(func, **make_jaxpr_kwargs)(*args, **kwargs)
  File ".../work/pennylane/catalyst/frontend/catalyst/jax_extras/tracing.py", line 555, in make_jaxpr_f
    jaxpr, out_type, consts = trace_to_jaxpr_dynamic2(f)
  File ".../.conda/envs/xanadu/lib/python3.9/site-packages/jax/_src/profiler.py", line 335, in wrapper
    return func(*args, **kwargs)
  File ".../.conda/envs/xanadu/lib/python3.9/site-packages/jax/_src/interpreters/partial_eval.py", line 2362, in trace_to_jaxpr_dynamic2
    jaxpr, out_type, consts = trace_to_subjaxpr_dynamic2(fun, main, debug_info)
  File ".../.conda/envs/xanadu/lib/python3.9/site-packages/jax/_src/interpreters/partial_eval.py", line 2377, in trace_to_subjaxpr_dynamic2
    ans = fun.call_wrapped(*in_tracers_)
  File ".../.conda/envs/xanadu/lib/python3.9/site-packages/jax/_src/linear_util.py", line 192, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File ".../work/pennylane/catalyst/frontend/catalyst/jit.py", line 608, in fn_with_transform_named_sequence
    return self.user_function(*args, **kwargs)
  File ".../work/pennylane/catalyst/frontend/test.py", line 68, in g
    jsp.linalg.expm(A)
  File ".../.conda/envs/xanadu/lib/python3.9/site-packages/jax/_src/scipy/linalg.py", line 1163, in expm
    R = lax.cond(n_squarings > max_squarings, _nan, _compute, (A, P, Q))
  File ".../.conda/envs/xanadu/lib/python3.9/site-packages/jax/_src/scipy/linalg.py", line 1159, in _compute
    R = _solve_P_Q(P, Q, upper_triangular)
  File ".../.conda/envs/xanadu/lib/python3.9/site-packages/jax/_src/scipy/linalg.py", line 1201, in _solve_P_Q
    return jnp.linalg.solve(Q, P)
  File ".../.conda/envs/xanadu/lib/python3.9/site-packages/jax/_src/numpy/linalg.py", line 1320, in solve
    return jnp.vectorize(lax_linalg._solve, signature=signature)(a, b)
  File ".../.conda/envs/xanadu/lib/python3.9/site-packages/jax/_src/numpy/vectorize.py", line 321, in wrapped
    result = vectorized_func(*squeezed_args)
  File ".../.conda/envs/xanadu/lib/python3.9/site-packages/jax/_src/numpy/vectorize.py", line 138, in wrapped
    out = func(*args)
NotImplementedError: Batching rule for 'gather' not implemented
```

Interestingly, if you call `solve` and `expm` within the same `@qjit` block, then it works:

```python
import numpy as np

import jax.numpy as jnp
import jax.scipy as jsp

from catalyst import qjit


rng = np.random.default_rng(42)


def good():
    A = jnp.array(rng.uniform(-1, 1, (3, 3)))
    b = jnp.array(rng.uniform(-1, 1, (3, 1)))

    @qjit
    def f(A, b):
        return jsp.linalg.solve(A, b), jsp.linalg.expm(A)

    return f(A, b)
```

```pycon
>>> solve_result, expm_result = good()
>>> print(solve_result)
[[ 0.76916628]
 [-0.19792595]
 [-0.75970703]]
>>> print(expm_result)
[[1.94944403 0.0351314  0.73593198]
 [0.62005861 0.57107875 0.63147519]
 [0.66094589 0.28554113 0.77824354]]
```

Note that I've run these examples with a modified version of Catalyst that provides the BLAS and LAPACK wrapper functions required by JAX.

### PR DESCRIPTION
**Pull request by paul0403**
**Context:**
There is a bug if multiple qjits call into `gather` primitive #1094 . With how we currently patch them, jax retains the first custom `gather2_p` object and keeps using that in the second run. 

**Description of the Change:**
Making sure there is only ever one `gather2_p` primitive object by pulling it out into patches.py as a global.
This way, jax will not complain about "gather batching rule not find", since we patch with the same gather2_p object every qjit run.

**Benefits:**
Multiple qjits in the same program can call into gather primitives. Although in the standard recommended usage there is just one qjit in the overall entry function, this unblocks potential pytests (where multiple qjits cannot be avoided).

**Related GitHub Issues:** closes #1094 , closes #894

[sc-72775]

### CODE REVIEW

**Review by joeycarter — APPROVED** [review]
Looks good, thanks @paul0403!

**Review by erick-xanadu — APPROVED** [review]
You are just moving the standard_primitive to the global scope, right? That sounds good. Do  you know if this also fixes these tests?

```
test/pytest/test_callback.py:@pytest.mark.parametrize("order", ["good", "bad"])
test/pytest/test_callback.py:def test_vjp_as_residual(arg, order):
test/pytest/test_callback.py:    if order == "bad":
test/pytest/test_callback.py:    if order == "bad":
test/pytest/test_callback.py:@pytest.mark.parametrize("order", ["good", "bad"])
test/pytest/test_callback.py:def test_vjp_as_residual_automatic(arg, order):
test/pytest/test_callback.py:    if order == "bad":
test/pytest/test_callback.py:    if order == "bad":
```

**Comment by paul0403** [comment]
> You are just moving the standard_primitive to the global scope, right? That sounds good. Do you know if this also fixes these tests?
> 
> ```
> test/pytest/test_callback.py:@pytest.mark.parametrize("order", ["good", "bad"])
> test/pytest/test_callback.py:def test_vjp_as_residual(arg, order):
> test/pytest/test_callback.py:    if order == "bad":
> test/pytest/test_callback.py:    if order == "bad":
> test/pytest/test_callback.py:@pytest.mark.parametrize("order", ["good", "bad"])
> test/pytest/test_callback.py:def test_vjp_as_residual_automatic(arg, order):
> test/pytest/test_callback.py:    if order == "bad":
> test/pytest/test_callback.py:    if order == "bad":
> ```

just checked, these are fixed as well

**Comment by erick-xanadu** [comment]
@paul0403 if you want, you can remove the skips in this commit or in another PR that follows. Happy with either.

**Comment by paul0403** [comment]
> @paul0403 if you want, you can remove the skips in this PR or in another one that follows. Happy with either.

I'll just unskip them here.

**Pull request merged**
