### PR TITLE
Fix nested verification

### LINKED ISSUE #1055: [BUG] Applying `adjoint` to a subroutine prior to a midcircuit measurement throws an error
#### Issue description

* *Expected behavior:* `adjoint` can be applied to gates and/or subroutines before and after mid-circuit measurements.

* *Actual behavior:* When `adjoint` is applied to a subroutine prior to a mid-circuit measurement, an error is raised that mid-circuit measurements are not invertible on the device, even if the adjointed function is applied to different qubits.

* *Reproduces how often:* Always

* *System information:* (post the output of `import pennylane as qml; qml.about()`)

```
Name: PennyLane
Version: 0.37.0
Summary: PennyLane is a cross-platform Python library for quantum computing, quantum machine learning, and quantum chemistry. Train a quantum computer the same way as a neural network.
Home-page: https://github.com/PennyLaneAI/pennylane
Author: 
Author-email: 
License: Apache License 2.0
Location: /home/olivia/.venv/catalyst/lib/python3.12/site-packages
Requires: appdirs, autograd, autoray, cachetools, networkx, numpy, packaging, pennylane-lightning, requests, rustworkx, scipy, semantic-version, toml, typing-extensions
Required-by: PennyLane-Catalyst, PennyLane_Lightning

Platform info:           Linux-6.8.0-41-generic-x86_64-with-glibc2.39
Python version:          3.12.3
Numpy version:           1.26.4
Scipy version:           1.12.0
Installed devices:
- lightning.qubit (PennyLane_Lightning-0.37.0)
- default.clifford (PennyLane-0.37.0)
- default.gaussian (PennyLane-0.37.0)
- default.mixed (PennyLane-0.37.0)
- default.qubit (PennyLane-0.37.0)
- default.qubit.autograd (PennyLane-0.37.0)
- default.qubit.jax (PennyLane-0.37.0)
- default.qubit.legacy (PennyLane-0.37.0)
- default.qubit.tf (PennyLane-0.37.0)
- default.qubit.torch (PennyLane-0.37.0)
- default.qutrit (PennyLane-0.37.0)
- default.qutrit.mixed (PennyLane-0.37.0)
- default.tensor (PennyLane-0.37.0)
- null.qubit (PennyLane-0.37.0)
- nvidia.custatevec (PennyLane-Catalyst-0.7.0)
- nvidia.cutensornet (PennyLane-Catalyst-0.7.0)
- oqc.cloud (PennyLane-Catalyst-0.7.0)
- softwareq.qpp (PennyLane-Catalyst-0.7.0)
```

#### Source code and tracebacks

Here is a minimal non-working example with a toggle-able bug.

```python
import pennylane as qml

from catalyst import adjoint, measure

def subroutine():
    qml.Hadamard(wires=1)

@qml.qjit()
@qml.qnode(qml.device("lightning.qubit", wires=2))
def circuit():
    # Comment/uncomment to toggle bug
    adjoint(subroutine)()

    res = measure(0)

    # This call is just to show that it works after the measurement
    adjoint(subroutine)()

    return res

print(circuit())
```

Below is the error message:

```
Traceback (most recent call last):
  File "/home/olivia/Code/shortalyst-dev/shor_isolate.py", line 11, in <module>
    @qml.qjit()
     ^^^^^^^^^^
  File "/home/olivia/.venv/catalyst/lib/python3.12/site-packages/pennylane/logging/decorators.py", line 61, in wrapper_entry
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/olivia/.venv/catalyst/lib/python3.12/site-packages/catalyst/jit.py", line 424, in qjit
    return QJIT(fn, CompileOptions(**kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olivia/.venv/catalyst/lib/python3.12/site-packages/pennylane/logging/decorators.py", line 65, in wrapper_exit
    output = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/olivia/.venv/catalyst/lib/python3.12/site-packages/catalyst/jit.py", line 491, in __init__
    self.aot_compile()
  File "/home/olivia/.venv/catalyst/lib/python3.12/site-packages/pennylane/logging/decorators.py", line 61, in wrapper_entry
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/olivia/.venv/catalyst/lib/python3.12/site-packages/catalyst/jit.py", line 525, in aot_compile
    self.jaxpr, self.out_type, self.out_treedef, self.c_sig = self.capture(
                                                              ^^^^^^^^^^^^^
  File "/home/olivia/.venv/catalyst/lib/python3.12/site-packages/catalyst/debug/instruments.py", line 143, in wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/olivia/.venv/catalyst/lib/python3.12/site-packages/pennylane/logging/decorators.py", line 61, in wrapper_entry
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/olivia/.venv/catalyst/lib/python3.12/site-packages/catalyst/jit.py", line 628, in capture
    jaxpr, out_type, treedef = trace_to_jaxpr(
                               ^^^^^^^^^^^^^^^
  File "/home/olivia/.venv/catalyst/lib/python3.12/site-packages/pennylane/logging/decorators.py", line 61, in wrapper_entry
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/olivia/.venv/catalyst/lib/python3.12/site-packages/catalyst/jax_tracer.py", line 531, in trace_to_jaxpr
    jaxpr, out_type, out_treedef = make_jaxpr2(func, **make_jaxpr_kwargs)(*args, **kwargs)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olivia/.venv/catalyst/lib/python3.12/site-packages/catalyst/jax_extras/tracing.py", line 539, in make_jaxpr_f
    jaxpr, out_type, consts = trace_to_jaxpr_dynamic2(f)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olivia/.venv/catalyst/lib/python3.12/site-packages/jax/_src/profiler.py", line 336, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/olivia/.venv/catalyst/lib/python3.12/site-packages/jax/_src/interpreters/partial_eval.py", line 2324, in trace_to_jaxpr_dynamic2
    jaxpr, out_type, consts = trace_to_subjaxpr_dynamic2(fun, main, debug_info)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olivia/.venv/catalyst/lib/python3.12/site-packages/jax/_src/interpreters/partial_eval.py", line 2339, in trace_to_subjaxpr_dynamic2
    ans = fun.call_wrapped(*in_tracers_)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olivia/.venv/catalyst/lib/python3.12/site-packages/jax/_src/linear_util.py", line 191, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olivia/.venv/catalyst/lib/python3.12/site-packages/pennylane/logging/decorators.py", line 61, in wrapper_entry
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/olivia/.venv/catalyst/lib/python3.12/site-packages/catalyst/qfunc.py", line 150, in __call__
    res_flat = func_p.bind(flattened_fun, *args_flat, fn=self)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olivia/.venv/catalyst/lib/python3.12/site-packages/jax/_src/core.py", line 2309, in bind
    outs = top_trace.process_call(self, fun_, tracers, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olivia/.venv/catalyst/lib/python3.12/site-packages/jax/_src/interpreters/partial_eval.py", line 2012, in process_call
    jaxpr, out_type, consts = trace_to_subjaxpr_dynamic2(f, self.main, debug_info=dbg)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olivia/.venv/catalyst/lib/python3.12/site-packages/jax/_src/interpreters/partial_eval.py", line 2339, in trace_to_subjaxpr_dynamic2
    ans = fun.call_wrapped(*in_tracers_)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olivia/.venv/catalyst/lib/python3.12/site-packages/jax/_src/linear_util.py", line 191, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olivia/.venv/catalyst/lib/python3.12/site-packages/catalyst/qfunc.py", line 139, in _eval_quantum
    closed_jaxpr, out_type, out_tree = trace_quantum_function(
                                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olivia/.venv/catalyst/lib/python3.12/site-packages/pennylane/logging/decorators.py", line 61, in wrapper_entry
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/olivia/.venv/catalyst/lib/python3.12/site-packages/catalyst/jax_tracer.py", line 1126, in trace_quantum_function
    tapes, post_processing = apply_transform(
                             ^^^^^^^^^^^^^^^^
  File "/home/olivia/.venv/catalyst/lib/python3.12/site-packages/pennylane/logging/decorators.py", line 61, in wrapper_entry
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/olivia/.venv/catalyst/lib/python3.12/site-packages/catalyst/jax_tracer.py", line 939, in apply_transform
    tapes, post_processing = total_program([tape])
                             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/olivia/.venv/catalyst/lib/python3.12/site-packages/pennylane/transforms/core/transform_program.py", line 515, in __call__
    new_tapes, fn = transform(tape, *targs, **tkwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olivia/.venv/catalyst/lib/python3.12/site-packages/catalyst/device/verification.py", line 225, in verify_operations
    _verify_nested(tape, (False, False), _op_checker)
  File "/home/olivia/.venv/catalyst/lib/python3.12/site-packages/catalyst/device/verification.py", line 51, in _verify_nested
    state = op_checker_fn(op, state)
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olivia/.venv/catalyst/lib/python3.12/site-packages/catalyst/device/verification.py", line 212, in _op_checker
    in_inverse = _inv_op_checker(op, in_inverse)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olivia/.venv/catalyst/lib/python3.12/site-packages/catalyst/device/verification.py", line 191, in _inv_op_checker
    raise CompileError(
catalyst.utils.exceptions.CompileError: MidCircuitMeasure is not invertible on 'lightning.qubit' device
```

### PR DESCRIPTION
**Pull request by erick-xanadu**
**Context:** Nested verification is incorrectly applied.

**Description of the Change:** Avoids overwriting the variable `state` with another scope's `state`.

**Related GitHub Issues:** Fixes #1055

[sc-72156]

### CODE REVIEW

**Comment by erick-xanadu** [comment]
This commit should be cherry-picked to RC.

**Comment by dime10** [comment]
> This commit should be cherry-picked to RC.

Why not merge to RC directly?

**Comment by erick-xanadu** [comment]
@dime10 I always find it easier to cherry pick to rc, but let me rebase.

**Review by dime10 — APPROVED** [review]
Thanks for fixing this! :)

**Pull request merged**
