### PR TITLE
:warning: :construction: Load plugins from python

### PR DESCRIPTION
**Pull request by erick-xanadu**
### Before submitting

Please complete the following checklist when submitting a PR:

- [ ] All new functions and code must be clearly commented and documented.

- [ ] Ensure that code is properly formatted by running `make format`.
      The latest version of black and `clang-format-14` are used in CI/CD to check formatting.

- [ ] All new features must include a unit test.
      Integration and frontend tests should be added to [`frontend/test`](../frontend/test/),
      Quantum dialect and MLIR tests should be added to [`mlir/test`](../mlir/test/), and
      Runtime tests should be added to [`runtime/tests`](../runtime/tests/).

When all the above are checked, delete everything above the dashed
line and fill in the pull request template.

------------------------------------------------------------------------------------------------------------

**Context:**

**Description of the Change:**

**Benefits:**

**Possible Drawbacks:**

**Related GitHub Issues:**

### CODE REVIEW

**Comment by erick-xanadu** [comment]
Note: the standalone plugin must be linked against compiler_driver.so and compiler_driver.so must be in standalone plugin's rpath. How to make sure third parties have good experience with this? Maybe Catalyst can provide some build flags to set them up correctly.

**Comment by dime10** [comment]
> Note: the standalone plugin must be linked against compiler_driver.so and compiler_driver.so must be in standalone plugin's rpath. How to make sure third parties have good experience with this? Maybe Catalyst can provide some build flags to set them up correctly.

Oh, so it's not dynamically loaded? 🤔

**Comment by erick-xanadu** [comment]
> Oh, so it's not dynamically loaded? 🤔

It is. It is dynamically linked and loaded. It just needs to know where to look for some symbols and I think it has to be the compiler_driver.so since it has all the LLVM symbols that the plugin needs. It is replacing the role of `mlir-opt`.

**Comment by dime10** [comment]
> > Oh, so it's not dynamically loaded? 🤔
> 
> It is. It is dynamically linked and loaded. It just needs to know where to look for some symbols and I think it has to be the compiler_driver.so since it has all the LLVM symbols that the plugin needs. It is replacing the role of `mlir-opt`.
> 
> EDIT: Maybe as a clarification, I think normally the dynamic linker will look for symbols in the current process, which would be `mlir-opt`. But in this case it is `python`. And for some reason it won't look in `compiler_driver.so` for those symbols unless the plugin has `compiler_driver.so` in its `NEEDED` ELF section.

I was thinking of something more akin to dlopen than dynamic linking. But I have no idea how the opt plugins work since I've never compiled one. I guess the problem in this case is that symbol dependency goes in both directions right?

**Comment by erick-xanadu** [comment]
> I was thinking of something more akin to dlopen than dynamic linking. But I have no idea how the opt plugins work since I've never compiled one. I guess the problem in this case is that symbol dependency goes in both directions right?

No. `compiler_driver.so` will never point to the plugin. But the plugin will have to point to `compiler_driver.so`. 

It is dlopen under the hood. But the problem is also dlopen :sweat_smile: . In Python, when libraries are loaded, they are loaded with RTLD_LOCAL. This means that when `compiler_driver.so` is loaded, its symbols are not shared with python. When the plugin is loaded by `compiler_driver.so` this is the search path looking for symbols by the dynamic linker:

```
   1357681:     symbol=_ZN4mlir4Pass17initializeOptionsEN4llvm9StringRefE;  lookup in file=python [0]
   1357681:     symbol=_ZN4mlir4Pass17initializeOptionsEN4llvm9StringRefE;  lookup in file=/home/ubuntu/.pyenv/versions/3.10.13-debug/lib/libpython3.10d.so.1.0 [0]
   1357681:     symbol=_ZN4mlir4Pass17initializeOptionsEN4llvm9StringRefE;  lookup in file=/lib/x86_64-linux-gnu/libc.so.6 [0]
   1357681:     symbol=_ZN4mlir4Pass17initializeOptionsEN4llvm9StringRefE;  lookup in file=/lib/x86_64-linux-gnu/libm.so.6 [0]
   1357681:     symbol=_ZN4mlir4Pass17initializeOptionsEN4llvm9StringRefE;  lookup in file=/lib64/ld-linux-x86-64.so.2 [0]
   1357681:     symbol=_ZN4mlir4Pass17initializeOptionsEN4llvm9StringRefE;  lookup in file=/home/ubuntu/code/catalyst/plugin/build/lib/StandalonePlugin.so [0]
   1357681:     symbol=_ZN4mlir4Pass17initializeOptionsEN4llvm9StringRefE;  lookup in file=/lib/x86_64-linux-gnu/libtinfo.so.6 [0]
   1357681:     symbol=_ZN4mlir4Pass17initializeOptionsEN4llvm9StringRefE;  lookup in file=/lib/x86_64-linux-gnu/libstdc++.so.6 [0]
   1357681:     symbol=_ZN4mlir4Pass17initializeOptionsEN4llvm9StringRefE;  lookup in file=/lib/x86_64-linux-gnu/libm.so.6 [0]
   1357681:     symbol=_ZN4mlir4Pass17initializeOptionsEN4llvm9StringRefE;  lookup in file=/lib/x86_64-linux-gnu/libgcc_s.so.1 [0]
   1357681:     symbol=_ZN4mlir4Pass17initializeOptionsEN4llvm9StringRefE;  lookup in file=/lib/x86_64-linux-gnu/libc.so.6 [0]
   1357681:     symbol=_ZN4mlir4Pass17initializeOptionsEN4llvm9StringRefE;  lookup in file=/lib64/ld-linux-x86-64.so.2 [0]
   1357681:     /home/ubuntu/code/catalyst/plugin/build/lib/StandalonePlugin.so: error: symbol lookup error: undefined symbol: _ZN4mlir4Pass17initializeOptionsEN4llvm9StringRefE (fatal)
```

When loading from mlir-opt, we would search mlir-opt instead of python. And we would succeed immediately. But because we are in python and the symbols are not available, it would continue looking. Without having the `compiler_driver.so` in the NEEDED section of the plugin, the plugin cannot find some symbols (as in the error shown above)

**Comment by erick-xanadu** [comment]
> I guess the problem in this case is that symbol dependency goes in both directions right?

Judging by this comment, you may have misread this statement

> the standalone plugin must be linked against compiler_driver.so and compiler_driver.so must be in standalone plugin's rpath

It means that:

* standalone plugin will have compiler_driver.so in its NEEDED section (the plugin points to compiler_driver.so).
* compiler_driver.so must be in the standalone plugin's rpath (the plugin points to compiler_driver.so)

**Comment by erick-xanadu** [comment]
```
(env) ubuntu@touched-stingray:~/code/catalyst/plugin$ readelf -d build/lib/StandalonePlugin.so 

Dynamic section at offset 0x57c18 contains 28 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [pybindopt.so] #<-- place holder for compiler_driver.so in my experiments
 0x0000000000000001 (NEEDED)             Shared library: [libstdc++.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x000000000000001d (RUNPATH)            Library runpath: [$ORIGIN/../lib:/home/ubuntu/code/catalyst/mlir/llvm-project/build/./lib:$ORIGIN/../..] # compiler_driver.so must be somewhere here.

 ```

**Comment by erick-xanadu** [comment]
> I was thinking of something more akin to dlopen than dynamic linking.

Also, regarding this, it is dlopen but only for a small subset of functions. The rest are dynamic linking. So all LLVM functions except the ones to initialize the dialect and passes are dynamic linking.

**Comment by dime10** [comment]
> > I guess the problem in this case is that symbol dependency goes in both directions right?
> 
> Judging by this comment, you may have misread this statement
> 
> > the standalone plugin must be linked against compiler_driver.so and compiler_driver.so must be in standalone plugin's rpath
> 
> It means that:
> 
> * standalone plugin will have compiler_driver.so in its NEEDED section (the plugin points to compiler_driver.so).
> * compiler_driver.so must be in the standalone plugin's rpath (the plugin points to compiler_driver.so)

Right, but I'm assuming the plugin needs to invoke mlir functions right? For the device backend plugins this is not the case for example, so the dependency is only one-way.

**Comment by erick-xanadu** [comment]
> Right, but I'm assuming the plugin needs to invoke mlir functions right? For the device backend plugins this is not the case for example, so the dependency is only one-way.

I'm not sure I understand what you are asking. Maybe we are agreeing? As we see from the concrete example I provided, the plugin is looking for `_ZN4mlir4Pass17initializeOptionsEN4llvm9StringRefE` (`mlir::Pass::initializeOptions(llvm::StringRef)`) and under mlir-opt it would be available in the parent process. This is an mlir function. So the question "Right, but I'm assuming the plugin needs to invoke mlir functions right?" is answered with yes.

 > For the device backend plugins this is not the case for example, so the dependency is only one-way.
 
 What do you mean by "device backend plugins"? I am here only talking about pass-plugin and dialect-plugin as described by MLIR. I have also answered above the kind of dependency the plugin will have on the compiler driver (it needs to be in the NEEDED section and the rpath needs to be correctly set to point to a location where compiler_driver.so can be found).

**Comment by dime10** [comment]
> > Right, but I'm assuming the plugin needs to invoke mlir functions right? For the device backend plugins this is not the case for example, so the dependency is only one-way.
> 
> I'm not sure I understand what you are asking. Maybe we are agreeing? As we see from the concrete example I provided, the plugin is looking for `_ZN4mlir4Pass17initializeOptionsEN4llvm9StringRefE` (`mlir::Pass::initializeOptions(llvm::StringRef)`) and under mlir-opt it would be available in the parent process. This is an mlir function. So the question "Right, but I'm assuming the plugin needs to invoke mlir functions right?" is answered with yes.
> 
> > For the device backend plugins this is not the case for example, so the dependency is only one-way.
> 
> What do you mean by "device backend plugins"? I am here only talking about pass-plugin and dialect-plugin as described by MLIR. I have also answered above the kind of dependency the plugin will have on the compiler driver (it needs to be in the NEEDED section and the rpath needs to be correctly set to point to a location where compiler_driver.so can be found).

Yes I think we're in agreement 👍

**Pull request closed without merging**
