### PR TITLE
[CI/CD] Run async tests when building wheels.

### LINKED ISSUE #509: Conditionally add "-lstdc++" when qnode's are executed asynchronously
The exception handling mechanism uses `@__gxx_personality_v0` which is defined in `-lstdc++` or `lc++`.

### PR DESCRIPTION
**Pull request by erick-xanadu**
Run async tests when building wheels. Also link against `-libstdc++` and `-lc++` as we now depend on the personality function `__gxx_personality_v0`.

Fixes #509

### CODE REVIEW

**Comment by dime10** [comment]
Any chance we can also remove the async test output? If we can help it our test suite should never print anything by default or produce warnings.

**Comment by dime10** [comment]
Can you add this PR to the existing changelog entry as well?

**Comment by erick-xanadu** [comment]
> For the non-deterministic bug you can just re-run those failing jobs.

I didn't find value in rerunning them as we know that it works and fails for a different reason. But sure, I'll re-run them :)

> Can you add this PR to the existing changelog entry as well?

It is already the case.

> Any chance we can also remove the async test output?

May I add this as an additional PR as opposed to in this one? They can definitely be removed, they are placed in a puts message in the MLIR. So just updating the async test to remove that operation should do the trick:

```
  tail call void @puts(ptr nonnull @assert_msg_7)
```

**Comment by dime10** [comment]
> It is already the case.
My bad 👍 

One last thing, I think we need to update the documentation because we now require a working C++ installation for users who use the package, whereas before we only required any compiler with a gcc cl interface. Looping @josh146 in for this discussion as well.

**Comment by josh146** [comment]
Just so I understand:

- If a user chooses to enable async, _then_ the frontend will try to load the C++ std library.
- But if they don't, the C++ std library isn't needed and nothing additional changes.

What are the user implications of now requiring the C++ std library?

- For MacOS users, does nothing change since we already require them to install Xcode?
- For linux users, we just have to update the installation command specify `libstdc++` to apt?

And maybe a final question, which is: should we consider a move to the LLVM JIT engine? Would that help solve anything?

**Comment by erick-xanadu** [comment]
> If a user chooses to enable async, then the frontend will try to load the C++ std library. But if they don't, the C++ std library isn't needed and nothing additional changes.

Correct on both of them. We can also just always include the CT++ std library even if we don't use async. (I do prefer that option)

> For MacOS users, does nothing change since we already require them to install Xcode?

I think so.

> For linux users, we just have to update the installation command specify libstdc++ to apt?

Maybe? I think many Ubuntu distro's come with libstdc++ by default since otherwise many programs wouldn't run?

**Review by dime10 — APPROVED** [review]
Ok I think I'm convinced that libstd++ will be available on linux, and for macos xcode has to be installed anyways.

**Pull request merged**
