### PR TITLE
[Frontend] Added test_broadcast_double_odd to test_template.py

### PR DESCRIPTION
**Pull request by ndcroos**
See issue https://github.com/PennyLaneAI/catalyst/issues/59
Parameters are taken from here:
https://docs.pennylane.ai/en/stable/code/api/pennylane.broadcast.html

### CODE REVIEW

**Comment by dime10** [comment]
Hi @ndcroos, welcome to Catalyst and thank you for contributing! 🙂 

The Catalyst team will be taking a look at your PR shortly. In general we use `black` and `isort` to format our Python files, you should be able to just run those on the frontend directory (`black frontend` and `isort frontend`, although isort shouldn't be needed unless you touch imports).
It also looks like the test you added is failing in the CI check:
```
FAILED frontend/test/pytest/test_template.py::test_broadcast_double_odd[lightning.qubit] - ValueError: Parameters must contain entries for 1 unitaries; got 3 entries
```
Was it passing locally?

**Comment by ndcroos** [comment]
Hi @dime10, thanks for the welcome. I followed the suggestion [here](https://discuss.pennylane.ai/t/error-running-make-test-targets-in-frontend-for-catalyst/3369/3?u=ndcroos) to use the CI on GitHub as way to test my work.

**Comment by ndcroos** [comment]
I am not sure how to specify the param.
See this: https://docs.pennylane.ai/en/stable/code/api/pennylane.broadcast.html
Here, M is the number of wires.

> pattern="double_odd" applies a two-wire unitary to ⌊(M−1)/2⌋
>  subsequent pairs of wires, starting with the second wire:

So if M = 4, then the double_odd pattern applies the unitary to 1 pair of wire, requiring 1 parameter (here [-5.3, 2.3, 3])?

**Comment by dime10** [comment]
Hi @ndcroos, I think your change in [7009853](https://github.com/PennyLaneAI/catalyst/pull/263/commits/7009853e68c54bee093c31e6f5d51724fe6838f2) fixed it. Because the given gate / unitary itself requires multiple parameters (in a list or array), you just needed an additional dimension in addition to the broadcast dimension.

At the moment our CI checks are temporarily disabled because we are updating our GitHub actions cache, but as soon as that is resolved we can proceed with your PR 🙂

**Comment by dime10** [comment]
Hi @ndcroos, you might need to revert your latest commit [a155b73](https://github.com/PennyLaneAI/catalyst/pull/263/commits/a155b73f821e88b4e30e1eb6a836615de2fcf078) as it seems to have changed the versions of our dependencies with respect to main.

**Comment by dime10** [comment]
Hi @ndcroos, I wanted to check in to see if you were still interested in contributing these tests? :)

**Comment by ndcroos** [comment]
Hi @dime10, thanks for coming back to me. At the moment, I haven't found time to continue yet. If anyone else wants to contribute these tests, and wants to use some part of these commits, they can do so. I will not further on this.

**Comment by dime10** [comment]
Thank you for working on this PR! I'll close it as stale now but feel free to reopen at any time if you wish to continue working on it :)

**Pull request closed without merging**
