### PR TITLE
Add minimal OpenQASM dialect support in MLIR

### LINKED ISSUE #873: OpenQASM generation in MLIR
**Context**

We would like to run a small experiment of adding an [OpenQASM](https://docs.quantum.ibm.com/build/introduction-to-qasm) dialect in [MLIR](https://mlir.llvm.org/). Having a native
representation of the OpenQASM standard available in MLIR would be beneficial in several ways,
like facilitating the translation of an OpenQASM text file into and out of MLIR, enabling
transformations on OpenQASM programs, and more generally improving inter-operability between tools.

**Goal**

For this experiment we would like to focus on the representation of OpenQASM in MLIR and its
translation to the OpenQASM text format.

For the first step, we would like to keep things simple and create a new [dialect](https://mlir.llvm.org/docs/LangRef/#dialects) called "OpenQASM"
with only three elements in it:
- a new allocation operation
- a new quantum operation for the RY gate
- a new quantum operation for the CNOT gate

Let's have a look at a simple OpenQASM program:

```
    OPENQASM 3.0;
    include "stdgates.inc";

    qubit[2] q;
    ry(0.7) q[0];
    cx q[0], q[1];
```

We can represent this program in MLIR using the dialect sketched out above, where the IR might look
something like this:

```
module {
    oq.allocate(5)
    oq.ry(0.7) 0
    oq.cnot 0, 1
}
```

We would then like to be able to traverse the MLIR and print out the program in the OpenQASM format.

**Technical Details**

A few more details on the dialect and operations which could be helpful:
  - the dialect prefix can be freely chosen, but `oq.` was used in the example
  - regarding the allocation operation
    - this operation only needs to set up a global qubit register based on the provided size
    - the OpenQASM name of register can be assumed fixed (`q` in the example) and known globally
  - the RY gate accepts a float parameter and a qubit register index, with no results
  - the CNOT/CX gate accepts two qubit register indices, with no results
  - [attributes](https://mlir.llvm.org/docs/LangRef/#attributes) (compile-time constants) can be used for all arguments, although SSA values can
    also be used if desired

The MLIR documentation has a few resources about defining new dialects, notably:
- [defining a dialect](https://mlir.llvm.org/docs/DefiningDialects/) (and its subpages, usage of ODS is strongly recommended)
- [dialect tutorial](https://mlir.llvm.org/docs/Tutorials/CreatingADialect/)

It will be easiest to set up the dialect in the existing [Catalyst source tree](https://github.com/PennyLaneAI/catalyst/tree/main/mlir).

It may also be helpful to look at the existing dialect files provided there, although for this
implementation the full structure does not need to be replicated. It would be sufficient to have a single
TableGen (`.td`), header (`.h`), and source (`.cpp`) file for the dialect components and the
translation pass, but other configurations are also fine.

For the translation pass, the method to produce the textual OpenQASM format from the IR can be
freely chosen, although one possible approach may simply iterate over the MLIR module and print the
equivalent OpenQASM out to console. See also:
- [MLIR passes](https://mlir.llvm.org/docs/PassManagement/)
- [understanding/traversing the IR](https://mlir.llvm.org/docs/Tutorials/UnderstandingTheIRStructure/)

The pass could then be registered with the [quantum-opt tool](https://github.com/PennyLaneAI/catalyst/blob/23e6d2bd9fcb41761e7cb362d4301cf3129e3f43/mlir/tools/quantum-opt/quantum-opt.cpp#L36) and run as
`quantum-opt --translate-to-openqasm example_ir.mlir`.

**Installation Help**

Refer to the [Catalyst installation guide](https://docs.pennylane.ai/projects/catalyst/en/latest/dev/installation.html) for how to install a source build of the project.

### PR DESCRIPTION
**Pull request by joeycarter**
**Context:**
Adding a native representation of the OpenQASM standard in MLIR.

**Description of the Change:**
- Add the OpenQASM dialect with support for three operations:
    - Qubit allocation
    - RY gate
    - CNOT gate
- Add support for a translation pass to produce a program in OpenQASM format from the IR.

**Benefits:**
Having native OpenQASM support in MLIR will, for example, help facilitate the translation of an OpenQASM text file into and out of MLIR, enable transformations on OpenQASM programs, and more generally improve inter-operability between tools.

**Possible Drawbacks:**
Only limited support for now.

**Related GitHub Issues:**
Resolves #873

### CODE REVIEW

**Comment by joeycarter** [comment]
This is my initial attempt at resolving issue #873. At the moment, the OpenQASM dialect I have implemented is not "aware" of what any of the operations do (qubit allocation, RY gate and CNOT gate); I have assumed this was not required for the issue at hand. The MLIR -> OpenQASM translation pass simply walks through the IR operations and prints to the console the equivalent OpenQASM statements (as suggested in the original issue description). However, because of the way the MLIR tools are implemented, this also prints the original IR after it, since the operations were not modified in any way. I'm curious if there's a solution to this.

**Comment by dime10** [comment]
Hi @joeycarter, thank you for the submission! I will have a look at it shortly :)

**Comment by dime10** [comment]
Nice work!! I don't really have any comments so this is great as is 🎉 

> However, because of the way the MLIR tools are implemented, this also prints the original IR after it, since the operations were not modified in any way. I'm curious if there's a solution to this.

Good point, this is just how the opt tool works I think. If you really wanted to you could probably output the openqasm to a different stream, and then redirect the regular opt output to /dev/null. But I think its fine.

**Comment by joeycarter** [comment]
Thanks @dime10! In that case I'll leave it as is.

**Pull request closed without merging**
