### PR TITLE
Remove deprecated pennylane code

### PR DESCRIPTION
**Pull request by mudit2812**
As name says. ~I've also temporarily added a warning filter to promote `PennyLaneDeprecationWarning`s to errors. I'll remove it once CI passes in this PR.~ Removed.

### CODE REVIEW

**Comment by mudit2812** [comment]
Proof of success [here](https://github.com/PennyLaneAI/catalyst/actions/runs/11133057613/job/30938413301?pr=1168). The reference to `qml._device.DeviceError` has now been fixed as well, and the `BasisStatePreparation` warning is coming from tests, not from catalyst, so I'm leaving it as is. Going to remove the warning to error promotion now.

**Comment by mudit2812** [comment]
[sc-73914]

**Review by lillian542 — APPROVED** [review]

**Comment by dime10** [comment]
>  and the `BasisStatePreparation` warning is coming from tests, not from catalyst, so I'm leaving it as is. Going to remove the warning to error promotion now.

What do you mean by this? Ideally we don't want warnings in our tests either :)

**Review by erick-xanadu — APPROVED** [review]
Are broadcast templates being deprecated? Why don't we just remove the tests?

**Pull request merged**
