### PR TITLE
[DOCS] Add an MLIR lexer to the documentation

### PR DESCRIPTION
**Pull request by josh146**

### CODE REVIEW

**Comment by josh146** [comment]
@dime10 I think it worked:

image

We just need to wait for the TableGen lexer to be merged into pygments and then we can syntax highlight those blocks as well

**Comment by dime10** [comment]
Fantastic 😍 Could you update the code blocks in the transformation guide to use the mlir lexer? :)

**Comment by josh146** [comment]
Done! Except I did it a little too fast and accidentally pushed it to your `dialect-guide` branch instead of this one 🤦 ca6098fd

**Comment by dime10** [comment]
I think it's not working for all code blocks unfortunately, like this first one:
Screenshot 2024-07-22 at 2 40 45 PM

**Comment by dime10** [comment]
Nice work! There are still some oddities with this version, but overall pretty nice.

For example, why is the `func.func` not formatted the same as other operations (instead it has the same colour as SSA values):
Screenshot 2024-07-23 at 11 44 37 AM

It looks like the same problem appears with these smaller snippets where every op is formatted this way:
Screenshot 2024-07-23 at 11 44 53 AM

Maybe something to do with global operations being treated differently than scoped operations?
It's the only issue I could find though.

**Comment by josh146** [comment]
> Maybe something to do with global operations being treated differently than scoped operations?

yeah that is my guess :(

**Comment by josh146** [comment]
@dime10 I think I found a fix for this: [e811b24](https://github.com/PennyLaneAI/catalyst/pull/950/commits/e811b24a6b7abe621a1ede4ac97c7441bd7d8480)

**Review by dime10 — APPROVED** [review]
Nice work! `func.func` is still red but this is great already :)

**Pull request merged**
