### PR TITLE
Migration to free GitHub runner for Mac arm64

### PR DESCRIPTION
**Pull request by dime10**
Notes:
- cross-os archives working for source code (llvm, mhlo, etc): https://github.com/PennyLaneAI/catalyst/actions/runs/10201847076/job/28224683082
- only one Python version used for LLVM build cache
- cleanup of cache-key names

Todo:
- [x] get action working: https://github.com/PennyLaneAI/catalyst/actions/runs/10219152515
- [x] delete caches for previous runner:
  - macOS-ARM64-llvm-3a8316216807d64a586b971f51695e23883331f7-3.9-generic-build
  - macOS-ARM64-llvm-3a8316216807d64a586b971f51695e23883331f7-3.10-generic-build
  - macOS-ARM64-llvm-3a8316216807d64a586b971f51695e23883331f7-3.11-generic-build
  - macOS-ARM64-llvm-3a8316216807d64a586b971f51695e23883331f7-3.12-generic-build
  - macOS-ARM64-mhlo-89a891c986650c33df76885f5620e0a92150d90f-generic-build
  - macOS-ARM64-enzyme-3a8316216807d64a586b971f51695e23883331f7-v0.0.130-generic-build

[sc-70439]

### CODE REVIEW

**Comment by dime10** [comment]
Running final test here: https://github.com/PennyLaneAI/catalyst/actions/runs/10219807330

**Review by rauletorresc — COMMENTED** [review]
Just a minor comment: Adding -N to the patch command in the other workflows does not relate with the PR purpose. For maintainability, wouldn't it be better to make a separate PR for that? What do you think?

**Comment by dime10** [comment]
> Just a minor comment: Adding -N to the patch command in the other workflows does not relate with the PR purpose. For maintainability, wouldn't it be better to make a separate PR for that? What do you think?

Personally for such a small change the overhead doesn't really seem worth it.

**Review by rauletorresc — APPROVED** [review]

**Review by erick-xanadu — APPROVED** [review]
:partying_face:

**Pull request merged**
